export const albums = [
    {
        id: 1,
        name: 'Sun Ra: Space Is The Place',
        image: 'sun-ra.png',
        description: `an excellent introduction to Sun Ra's vast and free-form jazz catalog`,
        category: 'jazz',
        price: 20,
    },
    {
        id: 2,
        name: 'Os Mutantes: s/t',
        image: 'osmutantes.png',
        description: `the debut eponymous album by the Brazilian tropicalia band Os Mutantes`,
        category: 'tropicalia',
        price: 18,
    },
    {
        id: 3,
        name: 'Kate Bush: Hounds Of Love',
        image: 'kate-bush.png',
        description: `the fifth studio album by English singer-songwriter and musician Kate Bush`,
        category: 'Art Pop',
        price: 22,
    },
    {
        id: 4,
        name: 'Beach Boys: Pet Sounds',
        image: 'beach-boys.png',
        description: `Maybe the best record ever recorded?`,
        category: 'Pop',
        price: 21,
    },
    {
        id: 5,
        name: 'Sam Cooke: Live At The Harlem Square Club',
        image: 'sam-cooke.png',
        description: `the second live album by the American singer-songwriter Sam Cooke`,
        category: 'soul',
        price: 24,
    },
    {
        id: 6,
        name: 'Duster: Stratosphere',
        image: 'duster.png',
        description: `the debut studio album by American space-rock band Duster`,
        category: 'slowcore',
        price: 23,
    },
];